"""English -> katakana mappings for TTS preprocessing.

Large dictionary of tech/IT acronyms, product names, and loanwords that
Edge TTS would otherwise garble. Matched BEFORE the letter-by-letter
fallback in preprocessing.japanese.convert_acronym().

Matching precedence:
  1. Exact case match in ACRONYM_MAP
  2. Uppercased match in ACRONYM_MAP
  3. [A-Z]+\\d+ pattern (EC2, S3) -> letters + numbers
  4. 2-5 uppercase letters -> letter-by-letter
  5. Otherwise passed through as-is
"""

# English letter -> katakana
LETTER_MAP = {
    "A": "エー", "B": "ビー", "C": "シー", "D": "ディー", "E": "イー",
    "F": "エフ", "G": "ジー", "H": "エイチ", "I": "アイ", "J": "ジェー",
    "K": "ケー", "L": "エル", "M": "エム", "N": "エヌ", "O": "オー",
    "P": "ピー", "Q": "キュー", "R": "アール", "S": "エス", "T": "ティー",
    "U": "ユー", "V": "ブイ", "W": "ダブリュー", "X": "エックス", "Y": "ワイ",
    "Z": "ゼット",
}

# Digits -> English-style katakana (used for tech contexts like EC2=イーシーツー)
NUMBER_MAP = {
    "0": "ゼロ", "1": "ワン", "2": "ツー", "3": "スリー", "4": "フォー",
    "5": "ファイブ", "6": "シックス", "7": "セブン", "8": "エイト", "9": "ナイン",
}

ACRONYM_MAP = {
    # Data formats / protocols
    "JSON": "ジェイソン",
    "REST": "レスト",
    "SQL": "エスキューエル",
    "NULL": "ヌル",
    "CRUD": "クラッド",
    "GUI": "ジーユーアイ",
    "CLI": "シーエルアイ",
    "SSH": "エスエスエイチ",
    "SSL": "エスエスエル",
    "TLS": "ティーエルエス",
    "DNS": "ディーエヌエス",
    "TCP": "ティーシーピー",
    "UDP": "ユーディーピー",
    "VPN": "ブイピーエヌ",
    "VPC": "ブイピーシー",
    "IAM": "アイエーエム",
    "AWS": "エーダブリューエス",
    "GCP": "ジーシーピー",
    "ORM": "オーアールエム",
    "MVC": "エムブイシー",
    "DRY": "ドライ",
    "SOLID": "ソリッド",
    "CORS": "コース",
    "CSRF": "シーエスアールエフ",
    "XSS": "エックスエスエス",
    "JWT": "ジェーダブリューティー",
    "OAuth": "オーオース",
    "SAML": "サムル",
    "SSO": "エスエスオー",
    "MFA": "エムエフエー",
    "RBAC": "アールバック",
    "GDPR": "ジーディーピーアール",
    "PCI": "ピーシーアイ",
    "SOC": "ソック",
    "WAF": "ワフ",
    "DDoS": "ディードス",
    "CDN": "シーディーエヌ",
    "TTL": "ティーティーエル",
    "SSD": "エスエスディー",
    "IOPS": "アイオプス",
    "EBS": "イービーエス",
    "RDS": "アールディーエス",
    "SQS": "エスキューエス",
    "SNS": "エスエヌエス",
    "ECS": "イーシーエス",
    "EKS": "イーケーエス",
    "ALB": "エーエルビー",
    "NLB": "エヌエルビー",
    "AMI": "エーエムアイ",
    "KMS": "ケーエムエス",
    "ETL": "イーティーエル",
    "SSR": "エスエスアール",
    "CSR": "シーエスアール",
    "SEO": "エスイーオー",
    "DOM": "ドム",
    "CSS": "シーエスエス",
    "ARIA": "アリア",
    # Tooling
    "npm": "エヌピーエム",
    "yarn": "ヤーン",
    "pip": "ピップ",
    "git": "ギット",
    "Slack": "スラック",
    "Jira": "ジラ",
    "cron": "クーロン",
    "grep": "グレップ",
    "sudo": "スードゥー",
    "bash": "バッシュ",
    "vim": "ビム",
    "nginx": "エンジンエックス",
    "Redis": "レディス",
    "Kafka": "カフカ",
    # Frameworks / libraries
    "React": "リアクト",
    "Vue": "ビュー",
    "Node": "ノード",
    "async": "エイシンク",
    "await": "アウェイト",
    "props": "プロップス",
    "state": "ステート",
    "hook": "フック",
    "hooks": "フックス",
    "webpack": "ウェブパック",
    "TypeScript": "タイプスクリプト",
    "JavaScript": "ジャバスクリプト",
    "Python": "パイソン",
    "Prisma": "プリズマ",
    "Docker": "ドッカー",
    "Dockerfile": "ドッカーファイル",
    "Kubernetes": "クバネティス",
    "Terraform": "テラフォーム",
    "CloudFormation": "クラウドフォーメーション",
    "CloudWatch": "クラウドウォッチ",
    "CloudTrail": "クラウドトレイル",
    "CloudFront": "クラウドフロント",
    # AWS services
    "Lambda": "ラムダ",
    "Fargate": "ファーゲート",
    "Cognito": "コグニート",
    "DynamoDB": "ダイナモディービー",
    "Redshift": "レッドシフト",
    "Athena": "アテナ",
    "Glue": "グルー",
    "Kinesis": "キネシス",
    "EventBridge": "イベントブリッジ",
    "CodeBuild": "コードビルド",
    "CodeDeploy": "コードデプロイ",
    "CodePipeline": "コードパイプライン",
    # Observability
    "Datadog": "データドッグ",
    "Grafana": "グラファナ",
    "Prometheus": "プロメテウス",
    "Splunk": "スプランク",
    "Sentry": "セントリー",
    "Okta": "オクタ",
    "Memcached": "メムキャッシュド",
    "RabbitMQ": "ラビットエムキュー",
    "Parquet": "パーケット",
    "Flexbox": "フレックスボックス",
    "Lighthouse": "ライトハウス",
    "RESTful": "レストフル",
    "GitHub": "ギットハブ",
    "GitLab": "ギットラブ",
    "DevOps": "デブオプス",
    "DevTools": "デブツールズ",
    "localhost": "ローカルホスト",
    "frontend": "フロントエンド",
    "backend": "バックエンド",
    "fullstack": "フルスタック",
    "middleware": "ミドルウェア",
    "microservice": "マイクロサービス",
    "microservices": "マイクロサービス",
    "monolith": "モノリス",
    "serverless": "サーバーレス",
    "webhook": "ウェブフック",
    "AI": "エーアイ",
    "README": "リードミー",
    "websocket": "ウェブソケット",
    "WebSocket": "ウェブソケット",
    # HTTP methods
    "GET": "ゲット",
    "POST": "ポスト",
    "PUT": "プット",
    "PATCH": "パッチ",
    "DELETE": "デリート",
    "HEAD": "ヘッド",
    "OK": "オーケー",
    "HTTP": "エイチティーティーピー",
    "HTTPS": "エイチティーティーピーエス",
    "HTML": "エイチティーエムエル",
    "URL": "ユーアールエル",
    # SQL keywords
    "SELECT": "セレクト",
    "INSERT": "インサート",
    "UPDATE": "アップデート",
    "WHERE": "ウェア",
    "ORDER": "オーダー",
    "GROUP": "グループ",
    "LIMIT": "リミット",
    "BY": "バイ",
    # Git terms
    "main": "メイン",
    "origin": "オリジン",
    "blame": "ブレーム",
    "upstream": "アップストリーム",
    "changelog": "チェンジログ",
    "install": "インストール",
    # Code keywords
    "null": "ナル",
    "true": "トゥルー",
    "false": "フォールス",
    "undefined": "アンデファインド",
    "boolean": "ブーリアン",
    "default": "デフォルト",
    "promise": "プロミス",
    "console": "コンソール",
    "log": "ログ",
    "try": "トライ",
    "catch": "キャッチ",
    "save": "セーブ",
    "limit": "リミット",
    "id": "アイディー",
    "env": "エンブ",
    "components": "コンポーネンツ",
    "utils": "ユーティルズ",
    "users": "ユーザーズ",
    "user": "ユーザー",
    "isActive": "イズアクティブ",
    # Tech products and frameworks
    "Safari": "サファリ",
    "GraphQL": "グラフキューエル",
    "Express": "エクスプレス",
    "NoSQL": "ノーエスキューエル",
    "ConfigMap": "コンフィグマップ",
    "ElastiCache": "エラスティキャッシュ",
    "lodash": "ロダッシュ",
    "bcrypt": "ビークリプト",
    # Abbreviations
    "TODO": "トゥードゥー",
    "FIXME": "フィックスミー",
    "E2E": "イーツーイー",
    "IaC": "アイエーシー",
    "for": "フォー",
    "if": "イフ",
    "else": "エルス",
    "at": "アット",
    "created": "クリエイテッド",
    "User": "ユーザー",
    "Secrets": "シークレッツ",
    "Cookie": "クッキー",
    "Grid": "グリッド",
    "Blob": "ブロブ",
    # AWS service components
    "Route": "ルート",
    "Gateway": "ゲートウェイ",
    "Ray": "レイ",
    "Manager": "マネージャー",
    "Parameter": "パラメーター",
    "Store": "ストア",
    "Step": "ステップ",
    "Functions": "ファンクションズ",
    "Cost": "コスト",
    "Explorer": "エクスプローラー",
    "New": "ニュー",
    "Relic": "レリック",
    "DTO": "ディーティーオー",
    "API": "エーピーアイ",
    "SDK": "エスディーケー",
    "CSV": "シーエスブイ",
    "XML": "エックスエムエル",
    "UI": "ユーアイ",
    "UX": "ユーエックス",
    "QA": "キューエー",
    "PR": "ピーアール",
    "CI": "シーアイ",
    "CD": "シーディー",
    "DB": "ディービー",
    "IP": "アイピー",
    "ID": "アイディー",
    "TDD": "ティーディーディー",
    "APM": "エーピーエム",
    "SLA": "エスエルエー",
    "SLO": "エスエルオー",
    "SLI": "エスエルアイ",
    "OKR": "オーケーアール",
    "KPI": "ケーピーアイ",
    "ETA": "イーティーエー",
    "DM": "ディーエム",
    "AES": "エーイーエス",
    # Alphanumeric abbreviations
    "K8s": "クバネティス",
    "a11y": "アクセシビリティ",
    "i18n": "国際化",
    "l10n": "ローカライゼーション",
    # Units
    "ms": "ミリ秒",
    "MB": "メガバイト",
    "GB": "ギガバイト",
    "TB": "テラバイト",
    "KB": "キロバイト",
    "Mbps": "メガビーピーエス",
    "Gbps": "ギガビーピーエス",
}

# Kanji that Edge TTS misreads. extract_furigana() substitutes the
# bracketed reading instead of keeping the kanji for these entries.
#
# HOW TO FIX A TTS MISREADING:
#   1. Add the kanji to this set.
#   2. Keep the CSV Pronunciation field as 漢字【reading】 (do NOT edit CSV).
#   3. Regenerate audio.
#   The override handles TTS while preserving card display.
TTS_KANJI_OVERRIDES: set[str] = {"型"}
